<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ArtisteSeeder extends Seeder
{
    public function run()
    {
        // Désactiver contraintes FK pour permettre truncate
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('artistes')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $now = date('Y-m-d H:i:s');

        DB::table('artistes')->insert([
            [
                'name' => 'Rock 109',
                'style' => 'Reprises rock des années 70 à aujourd’hui',
                'description' => "Rock 109, c’est un trio étonnant et détonnant qui revisite avec fougue les grands classiques du rock, des années 70 jusqu’à nos jours.\nUn show plein d’énergie pour ouvrir le festival en beauté et faire vibrer le public dès les premiers riffs. Prépare-toi à secouer la tête !",
                'photo' => 'img/artists/photos/Photos_artistes/ROCK 109.webp',
                'day' => 'Vendredi',
                'begin_date' => '2025-09-12 20:00:00',
                'ending_date' => '2025-09-12 21:30:00',
                'scene' => 'Extérieur',
                'soundcloud_url' => null,
                'spotify_url' => null,
                'youtube_url' => null,
                'deezer_url' => null,
                'actif' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'La Rif et Nos Men',
                'style' => 'Rap-Rock festif et engagé',
                'description' => "La Rif et Nos Men, c’est une histoire de famille et de musique. Deux frères, Léo et Tonio, bercés par le hip-hop, rejoints par leurs parents musiciens à l’accordéon et à la guitare, pour un cocktail unique de rap-rock festif.\nLeur son mêle des messages engagés (écologie, inégalités) à des textes plus poétiques, portés par une énergie communicative et une complicité sincère.\nUn vrai moment de partage, entre groove, conscience et chaleur humaine.",
                'photo' => 'img/artists/photos/Photos_artistes/LA RIF ET NOS MEN.webp',
                'day' => 'Vendredi',
                'begin_date' => '2025-09-12 21:00:00',
                'ending_date' => '2025-09-12 22:30:00',
                'scene' => 'Intérieur',
                'soundcloud_url' => 'https://soundcloud.com/toniorina',
                'spotify_url' => null,
                'youtube_url' => 'https://music.youtube.com/channel/UCqyjRgA71R8A0jCuopYEbhA',
                'deezer_url' => 'https://www.deezer.com/fr/artist/75987212',
                'actif' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => "An'Om x Vayn",
                'style' => 'Rap & électro mélodique',
                'description' => "Entre flow précis et ambiance électronique puissante, An’Om x Vayn font exploser les frontières musicales. An’Om livre ses émotions avec justesse pendant que Vayn sublime le tout avec ses productions.\nLe duo, révélé par leur hit \"Astronaute\", enchaîne les titres forts comme \"À mes démons\", introspectif et percutant.\nSur scène, leur complicité est palpable : un vrai show énergique et sensible, entre kick, partage et frissons.",
                'photo' => "img/artists/photos/Photos_artistes/AN'OM X VAYN.webp",
                'day' => 'Vendredi',
                'begin_date' => '2025-09-12 22:30:00',
                'ending_date' => '2025-09-13 00:00:00',
                'scene' => 'Extérieur',
                'soundcloud_url' => 'https://soundcloud.com/anomxvayn',
                'spotify_url' => null,
                'youtube_url' => null,
                'deezer_url' => null,
                'actif' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Wazy',
                'style' => 'DJ set – hip-hop, afro, house, rap',
                'description' => "Wazy, artiste plurielle et passionnée, fait vibrer les platines comme les cœurs. Passée par le chant, la batterie, la guitare et le piano, elle propose aujourd’hui un DJ set éclectique mêlant hip-hop, afro, house et rap avec une fluidité rare.\nSon objectif : créer un voyage sonore intense et joyeux, célébrant la diversité et l’unité par la musique.",
                'photo' => 'img/artists/photos/Photos_artistes/WAZY.webp',
                'day' => 'Vendredi',
                'begin_date' => '2025-09-13 00:00:00',
                'ending_date' => '2025-09-13 02:00:00',
                'scene' => 'Extérieur',
                'soundcloud_url' => 'https://soundcloud.com/user-630239260',
                'spotify_url' => null,
                'youtube_url' => null,
                'deezer_url' => null,
                'actif' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'AXL R.',
                'style' => 'House, Afro house, Disco house, Techno, Hard techno',
                'description' => "Figure bien connue de la scène nantaise, AXL R. fait vibrer les platines depuis plus de 12 ans. Des clubs aux festivals, il distille un mix percutant et polyvalent.",
                'photo' => "img/artists/photos/Photos_artistes/AXL R..webp",
                'day' => 'Vendredi',
                'begin_date' => '2025-09-13 00:30:00',
                'ending_date' => '2025-09-13 02:00:00',
                'scene' => 'Intérieur',
                'soundcloud_url' => 'https://soundcloud.com/dj-axl-r',
                'spotify_url' => null,
                'youtube_url' => null,
                'deezer_url' => null,
                'actif' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Hono',
                'style' => 'Electro House / Généraliste',
                'description' => "HONO, c’est l’assurance d’un set fédérateur et explosif. A l'aise aussi bien dans l'électro house que dans un registre plus généraliste.",
                'photo' => 'img/artists/photos/Photos_artistes/HONO.webp',
                'day' => 'Vendredi',
                'begin_date' => '2025-09-13 02:00:00',
                'ending_date' => '2025-09-13 04:00:00',
                'scene' => 'Extérieur',
                'soundcloud_url' => null,
                'spotify_url' => null,
                'youtube_url' => null,
                'deezer_url' => null,
                'actif' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Dymeister',
                'style' => 'Techno – Acid – Hard Trance',
                'description' => "Place aux vibrations brutes et sans compromis avec DYMEISTER, architecte sonore des nuits les plus intenses.",
                'photo' => 'img/artists/photos/Photos_artistes/DYMEISTER.webp',
                'day' => 'Vendredi',
                'begin_date' => '2025-09-13 02:00:00',
                'ending_date' => '2025-09-13 03:30:00',
                'scene' => 'Intérieur',
                'soundcloud_url' => 'https://soundcloud.com/dylan-chevalier-56586261',
                'spotify_url' => null,
                'youtube_url' => null,
                'deezer_url' => null,
                'actif' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // Samedi (exemples)
            [
                'name' => 'Youth Collective',
                'style' => 'Reggae Roots & Dub UK – Sound System',
                'description' => "Né en 2015 autour de la culture sound system nantaise, Youth Collective rassemble six passionnés.",
                'photo' => 'img/artists/photos/Photos_artistes/YOUTH COLLECTIVE.webp',
                'day' => 'Samedi',
                'begin_date' => '2025-09-13 15:00:00',
                'ending_date' => '2025-09-13 17:00:00',
                'scene' => 'Extérieur',
                'soundcloud_url' => null,
                'spotify_url' => null,
                'youtube_url' => null,
                'deezer_url' => null,
                'actif' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Maklos',
                'style' => 'House / Techno – Old School & Underground',
                'description' => "Maklos est un DJ et producteur qui fait le lien entre house old school et techno underground.",
                'photo' => 'img/artists/photos/Photos_artistes/MAKLOS.webp',
                'day' => 'Samedi',
                'begin_date' => '2025-09-13 17:00:00',
                'ending_date' => '2025-09-13 18:30:00',
                'scene' => 'Extérieur',
                'soundcloud_url' => 'https://soundcloud.com/maklosmusic',
                'spotify_url' => null,
                'youtube_url' => 'https://music.youtube.com/channel/UC3oi2p8BmFFb4k3YhkgOdNA',
                'deezer_url' => null,
                'actif' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Klö',
                'style' => 'Electro',
                'description' => "Klö, DJ émergente de la scène locale, fait partie de cette nouvelle génération qui électrise les platines avec style et audace.\nAvec ses mix envoûtants et ses sélections percutantes, elle promet un set qui fait bouger les corps et monte en intensité à mesure que le soleil décline.",
                'photo' => 'img/artists/photos/Photos_artistes/KLÖ.webp',
                'day' => 'Samedi',
                'begin_date' => '2025-09-13 18:30:00',
                'ending_date' => '2025-09-13 19:30:00',
                'scene' => 'Extérieur',
                'soundcloud_url' => null,
                'spotify_url' => null,
                'youtube_url' => null,
                'deezer_url' => null,
                'actif' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Kaboum',
                'style' => null,
                'description' => null,
                'photo' => 'img/artists/photos/Photos_artistes/KABOUM.webp',
                'day' => 'Samedi',
                'begin_date' => '2025-09-13 19:30:00',
                'ending_date' => '2025-09-13 21:00:00',
                'scene' => 'Extérieur',
                'soundcloud_url' => null,
                'spotify_url' => null,
                'youtube_url' => null,
                'deezer_url' => null,
                'actif' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'TOM WORRF',
                'style' => null,
                'description' => null,
                'photo' => 'img/artists/photos/Photos_artistes/TOM WORRF.webp',
                'day' => 'Samedi',
                'begin_date' => '2025-09-13 20:30:00',
                'ending_date' => '2025-09-13 22:00:00',
                'scene' => 'Intérieur',
                'soundcloud_url' => null,
                'spotify_url' => null,
                'youtube_url' => 'https://music.youtube.com/channel/UCdJep-VuS_wqB_aNXEO9VPw',
                'deezer_url' => 'https://www.deezer.com/fr/artist/250327002',
                'actif' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => '2TH',
                'style' => null,
                'description' => null,
                'photo' => 'img/artists/photos/Photos_artistes/2TH.webp',
                'day' => 'Samedi',
                'begin_date' => '2025-09-13 22:00:00',
                'ending_date' => '2025-09-13 23:30:00',
                'scene' => 'Extérieur',
                'soundcloud_url' => 'https://soundcloud.com/user-86681471',
                'spotify_url' => null,
                'youtube_url' => 'https://music.youtube.com/channel/UCLP2wR6chac-0YlUPRJmb5A',
                'deezer_url' => 'https://www.deezer.com/fr/artist/278029',
                'actif' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Mūne',
                'style' => null,
                'description' => null,
                'photo' => 'img/artists/photos/Photos_artistes/MŪNE.webp',
                'day' => 'Samedi',
                'begin_date' => '2025-09-13 23:30:00',
                'ending_date' => '2025-09-14 02:00:00',
                'scene' => 'Extérieur',
                'soundcloud_url' => 'https://soundcloud.com/user-951350425-867779404',
                'spotify_url' => null,
                'youtube_url' => null,
                'deezer_url' => null,
                'actif' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Yonex',
                'style' => null,
                'description' => null,
                'photo' => 'img/artists/photos/Photos_artistes/YONEX.webp',
                'day' => 'Samedi',
                'begin_date' => '2025-09-14 00:30:00',
                'ending_date' => '2025-09-14 02:00:00',
                'scene' => 'Intérieur',
                'soundcloud_url' => null,
                'spotify_url' => null,
                'youtube_url' => null,
                'deezer_url' => null,
                'actif' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Leydon',
                'style' => null,
                'description' => null,
                'photo' => 'img/artists/photos/Photos_artistes/LEYDON.webp',
                'day' => 'Samedi',
                'begin_date' => '2025-09-14 02:00:00',
                'ending_date' => '2025-09-14 04:00:00',
                'scene' => 'Extérieur',
                'soundcloud_url' => null,
                'spotify_url' => null,
                'youtube_url' => null,
                'deezer_url' => 'https://www.deezer.com/fr/artist/9308144',
                'actif' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Tripidium',
                'style' => null,
                'description' => null,
                'photo' => 'img/artists/photos/Photos_artistes/TRIPIDIUM.webp',
                'day' => 'Samedi',
                'begin_date' => '2025-09-14 02:00:00',
                'ending_date' => '2025-09-14 03:30:00',
                'scene' => 'Intérieur',
                'soundcloud_url' => 'https://soundcloud.com/iav-498336354',
                'spotify_url' => null,
                'youtube_url' => null,
                'deezer_url' => null,
                'actif' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // artiste supplémentaire inactif demandé
            [
                'name' => 'Charlzouu',
                'style' => 'Indé / Demo',
                'description' => "Projet interne de test pour Calan'Couleurs. Artiste fictif utilisé pour validation et tests.",
                'photo' => 'img/artists/photos/Photos_artistes/CHARLZOUU.webp',
                'day' => 'Samedi',
                'begin_date' => '2025-09-13 20:00:00',
                'ending_date' => '2025-09-13 21:00:00',
                'scene' => 'Intérieur',
                'soundcloud_url' => null,
                'spotify_url' => null,
                'youtube_url' => null,
                'deezer_url' => null,
                'actif' => 0,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);
    }
}
