<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ArtisteSeeder extends Seeder
{
    public function run()
    {
        // Désactiver contraintes FK pour permettre truncate
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('artistes')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $now = date('Y-m-d H:i:s');

        DB::table('artistes')->insert([
            [
                'name' => 'Rock 109',
                'style' => 'Reprises rock des années 70 à aujourd’hui',
                'description' => "Rock 109, c’est un trio étonnant et détonnant qui revisite avec fougue les grands classiques du rock, des années 70 jusqu’à nos jours.\nUn show plein d’énergie pour ouvrir le festival en beauté et faire vibrer le public dès les premiers riffs. Prépare-toi à secouer la tête !",
                'photo' => 'img/artists/photos/Photos_artistes/ROCK 109.webp',
                'soundcloud_url' => null,
                'spotify_url' => null,
                'youtube_url' => null,
                'deezer_url' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'La Rif et Nos Men',
                'style' => 'Rap-Rock festif et engagé',
                'description' => "La Rif et Nos Men, c’est une histoire de famille et de musique. Deux frères, Léo et Tonio, bercés par le hip-hop, rejoints par leurs parents musiciens à l’accordéon et à la guitare, pour un cocktail unique de rap-rock festif.\nLeur son mêle des messages engagés (écologie, inégalités) à des textes plus poétiques, portés par une énergie communicative et une complicité sincère.\nUn vrai moment de partage, entre groove, conscience et chaleur humaine.",
                'photo' => 'img/artists/photos/Photos_artistes/LA RIF ET NOS MEN.webp',
                'soundcloud_url' => 'https://soundcloud.com/toniorina',
                'spotify_url' => null,
                'youtube_url' => 'https://music.youtube.com/channel/UCqyjRgA71R8A0jCuopYEbhA',
                'deezer_url' => 'https://www.deezer.com/fr/artist/75987212',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => "An'Om x Vayn",
                'style' => 'Rap & électro mélodique',
                'description' => "Entre flow précis et ambiance électronique puissante, An’Om x Vayn font exploser les frontières musicales. An’Om livre ses émotions avec justesse pendant que Vayn sublime le tout avec ses productions.\nLe duo, révélé par leur hit \"Astronaute\", enchaîne les titres forts comme \"À mes démons\", introspectif et percutant.\nSur scène, leur complicité est palpable : un vrai show énergique et sensible, entre kick, partage et frissons.",
                'photo' => "img/artists/photos/Photos_artistes/AN'OM X VAYN.webp",
                'soundcloud_url' => 'https://soundcloud.com/anomxvayn',
                'spotify_url' => null,
                'youtube_url' => null,
                'deezer_url' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Wazy',
                'style' => 'DJ set – hip-hop, afro, house, rap',
                'description' => "Wazy, artiste plurielle et passionnée, fait vibrer les platines comme les cœurs. Passée par le chant, la batterie, la guitare et le piano, elle propose aujourd’hui un DJ set éclectique mêlant hip-hop, afro, house et rap avec une fluidité rare.\nSon objectif : créer un voyage sonore intense et joyeux, célébrant la diversité et l’unité par la musique.",
                'photo' => 'img/artists/photos/Photos_artistes/WAZY.webp',
                'soundcloud_url' => 'https://soundcloud.com/user-630239260',
                'spotify_url' => null,
                'youtube_url' => null,
                'deezer_url' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'AXL R.',
                'style' => 'House, Afro house, Disco house, Techno, Hard techno',
                'description' => 'Figure bien connue de la scène nantaise, AXL R. fait vibrer les platines depuis plus de 12 ans. Des clubs aux festivals, il distille un mix percutant et polyvalent.',
                'photo' => 'img/artists/photos/Photos_artistes/AXL R..webp',
                'soundcloud_url' => 'https://soundcloud.com/dj-axl-r',
                'spotify_url' => null,
                'youtube_url' => null,
                'deezer_url' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Hono',
                'style' => 'Electro House / Généraliste',
                'description' => "HONO, c’est l’assurance d’un set fédérateur et explosif. A l'aise aussi bien dans l'électro house que dans un registre plus généraliste.",
                'photo' => 'img/artists/photos/Photos_artistes/HONO.webp',
                'soundcloud_url' => null,
                'spotify_url' => null,
                'youtube_url' => null,
                'deezer_url' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Dymeister',
                'style' => 'Techno – Acid – Hard Trance',
                'description' => 'Place aux vibrations brutes et sans compromis avec DYMEISTER, architecte sonore des nuits les plus intenses.',
                'photo' => 'img/artists/photos/Photos_artistes/DYMEISTER.webp',
                'soundcloud_url' => 'https://soundcloud.com/dylan-chevalier-56586261',
                'spotify_url' => null,
                'youtube_url' => null,
                'deezer_url' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // Samedi (exemples)
            [
                'name' => 'Youth Collective',
                'style' => 'Reggae Roots & Dub UK – Sound System',
                'description' => 'Né en 2015 autour de la culture sound system nantaise, Youth Collective rassemble six passionnés.',
                'photo' => 'img/artists/photos/Photos_artistes/YOUTH COLLECTIVE.webp',
                'soundcloud_url' => null,
                'spotify_url' => null,
                'youtube_url' => null,
                'deezer_url' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Maklos',
                'style' => 'House / Techno – Old School & Underground',
                'description' => 'Maklos est un DJ et producteur qui fait le lien entre house old school et techno underground.',
                'photo' => 'img/artists/photos/Photos_artistes/MAKLOS.webp',
                'soundcloud_url' => 'https://soundcloud.com/maklosmusic',
                'spotify_url' => null,
                'youtube_url' => 'https://music.youtube.com/channel/UC3oi2p8BmFFb4k3YhkgOdNA',
                'deezer_url' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Klö',
                'style' => 'Electro',
                'description' => "Klö, DJ émergente de la scène locale, fait partie de cette nouvelle génération qui électrise les platines avec style et audace.\nAvec ses mix envoûtants et ses sélections percutantes, elle promet un set qui fait bouger les corps et monte en intensité à mesure que le soleil décline.",
                'photo' => 'img/artists/photos/Photos_artistes/KLÖ.webp',
                'soundcloud_url' => null,
                'spotify_url' => null,
                'youtube_url' => null,
                'deezer_url' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Kaboum',
                'style' => null,
                'description' => null,
                'photo' => 'img/artists/photos/Photos_artistes/KABOUM.webp',
                'soundcloud_url' => null,
                'spotify_url' => null,
                'youtube_url' => null,
                'deezer_url' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'TOM WORRF',
                'style' => null,
                'description' => null,
                'photo' => 'img/artists/photos/Photos_artistes/TOM WORRF.webp',
                'soundcloud_url' => null,
                'spotify_url' => null,
                'youtube_url' => 'https://music.youtube.com/channel/UCdJep-VuS_wqB_aNXEO9VPw',
                'deezer_url' => 'https://www.deezer.com/fr/artist/250327002',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => '2TH',
                'style' => null,
                'description' => null,
                'photo' => 'img/artists/photos/Photos_artistes/2TH.webp',
                'soundcloud_url' => 'https://soundcloud.com/user-86681471',
                'spotify_url' => null,
                'youtube_url' => 'https://music.youtube.com/channel/UCLP2wR6chac-0YlUPRJmb5A',
                'deezer_url' => 'https://www.deezer.com/fr/artist/278029',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Mūne',
                'style' => null,
                'description' => null,
                'photo' => 'img/artists/photos/Photos_artistes/MŪNE.webp',
                'soundcloud_url' => 'https://soundcloud.com/user-951350425-867779404',
                'spotify_url' => null,
                'youtube_url' => null,
                'deezer_url' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Yonex',
                'style' => null,
                'description' => null,
                'photo' => 'img/artists/photos/Photos_artistes/YONEX.webp',
                'soundcloud_url' => null,
                'spotify_url' => null,
                'youtube_url' => null,
                'deezer_url' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Leydon',
                'style' => null,
                'description' => null,
                'photo' => 'img/artists/photos/Photos_artistes/LEYDON.webp',
                'soundcloud_url' => null,
                'spotify_url' => null,
                'youtube_url' => null,
                'deezer_url' => 'https://www.deezer.com/fr/artist/9308144',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Tripidium',
                'style' => null,
                'description' => null,
                'photo' => 'img/artists/photos/Photos_artistes/TRIPIDIUM.webp',
                'soundcloud_url' => 'https://soundcloud.com/iav-498336354',
                'spotify_url' => null,
                'youtube_url' => null,
                'deezer_url' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // artiste supplémentaire qui sera inactif pour l'édition 2025
            [
                'name' => 'Charlzouu',
                'style' => 'Indé / Demo',
                'description' => "Projet interne de test pour Calan'Couleurs. Artiste fictif utilisé pour validation et tests.",
                'photo' => 'img/artists/photos/Photos_artistes/CHARLZOUU.webp',
                'soundcloud_url' => null,
                'spotify_url' => null,
                'youtube_url' => null,
                'deezer_url' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'SPIZER ZED',
                'style' => 'Rap & Pop mélancolique',
                'description' => "Auteur-compositeur Spider ZED s’est imposé comme une voix authentique de la scène française, avec plus de 70 millions de streams entre 2017 et 2023. Après l’album à succès Jeune intermittent et un accueil critique positif pour Club de cœur (2023), il poursuit son exploration des émotions du quotidien avec Joue le jeu, un EP sorti en 2024. Sa musique, drôle et mélancolique, capte le spleen d'une génération.",
                'photo' => 'img/artists/photos/Photos_artistes/SPIDER ZED.webp',
                'soundcloud_url' => null,
                'spotify_url' => 'https://open.spotify.com/intl-fr/artist/4kAzmAcboZ0F6bCCb4jj8I?si=7dmEUYrwTy-Bd81feemMDg',
                'youtube_url' => 'https://www.youtube.com/@SpiderZED',
                'deezer_url' => 'https://link.deezer.com/s/3349LucasWqmFEEgkEK05',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'OASIS',
                'style' => 'Electro',
                'description' => "DJ membre du collectif Fontn’r, il aime redonner vie aux classiques avec une touche groovy techno. Entre nostalgie assumée et énergie moderne, ses sets sont pensés pour être immersifs, intenses et résolument taillés pour le dancefloor. Une chose est sûre : ça va vibrer, transpirer et danser fort.",
                'photo' => 'img/artists/photos/Photos_artistes/OASIS.webp',
                'soundcloud_url' => null,
                'spotify_url' => null,
                'youtube_url' => null,
                'deezer_url' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'SANS LACTOSE',
                'style' => 'Pop',
                'description' => "Duo formé par deux frères, Sans Lactose raconte depuis 2019 le passage de la jeunesse à l’âge adulte à travers un univers mêlant pop nostalgique et refrains entêtants. Influencés par Columbine, Paul McCartney, Christophe ou encore FAUVE, ils s’inscrivent dans la nouvelle scène pop française en explorant sans cesse de nouveaux horizons musicaux.",
                'photo' => 'img/artists/photos/Photos_artistes/SANS LACTOSE.webp',
                'soundcloud_url' => null,
                'spotify_url' => 'https://open.spotify.com/intl-fr/artist/5o9bgsy6gISpQ7FJszf34L?si=ojBOu6sqSw6nl4K3BeMZgQ',
                'youtube_url' => 'https://www.youtube.com/@SansLactoseOfficiel',
                'deezer_url' => 'https://link.deezer.com/s/334aOQAw5v5nPX3YyyYjG',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'PURE',
                'style' => 'Pop',
                'description' => "Habitués des scènes et des festivals, PURE propose une expérience musicale à part : une alliance parfaite entre harmonies vocales, rythmes dansants et mélodies entêtantes. Originaire de Rennes, cette bande de copains transmet sur scène une énergie débordante et un amour sincère de la musique. Entre douceur, pop et sonorités singulières comme la harpe celtique, ils nous promettent un moment fascinant",
                'photo' => 'img/artists/photos/Photos_artistes/PURE.webp',
                'soundcloud_url' => null,
                'spotify_url' => 'https://open.spotify.com/intl-fr/artist/0nLw7iGQ3F4tdff3AbTw5M?si=cDJtVz2STWews2Rq6ejzYQ',
                'youtube_url' => 'https://www.youtube.com/@legroupepure',
                'deezer_url' => 'https://link.deezer.com/s/3352PhBAYJN7ZlDT3WM1r',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'MIMOSA',
                'style' => 'Pop',
                'description' => "Basé à Nantes, Mimosa est un trio de chanson française pop aux sonorités indie et rock. À travers des textes imagés et une musique rythmée, le groupe nous embarque dans un véritable voyage entre nostalgie, souvenirs et émotions, avec la mer comme fil conducteur.",
                'photo' => 'img/artists/photos/Photos_artistes/MIMOSA.webp',
                'soundcloud_url' => null,
                'spotify_url' => 'https://open.spotify.com/intl-fr/artist/64XUJ8nVZaAZ8U42pvw7Rl?si=Ld-WLTKuTVmAILePiMcLeA',
                'youtube_url' => 'https://www.youtube.com/channel/UCSnAp6fKWug7NGcFaZYX2xQ',
                'deezer_url' => 'https://link.deezer.com/s/33532sSVd66eQw5ufiwOu',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'PARENTHÈSE',
                'style' => 'Rap',
                'description' => "Projet solo de DJUL, leader vocal du KKC Orchestra, Parenthèse propose un live rap intimiste : un micro, une platine et des textes sincères, portés par le partage, l’émotion et l’authenticité. Avec plus de 20 ans d’expérience et 600 concerts, il crée une vraie bulle, une pause musicale à vivre ensemble",
                'photo' => 'img/artists/photos/Photos_artistes/PARENTHÈSE.webp',
                'soundcloud_url' => null,
                'spotify_url' => null,
                'youtube_url' => null,
                'deezer_url' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'SINNA',
                'style' => 'Electro',
                'description' => "DJ française de 20 ans, Sinna s’est imposée sur la scène électro avec des sets énergiques et fédérateurs. Résidente au @warehousenantes, elle a déjà fait vibrer de nombreux clubs et événements partout en France, avec une culture musicale large et une seule mission : faire kiffer le public !",
                'photo' => 'img/artists/photos/Photos_artistes/SINNA.webp',
                'soundcloud_url' => null,
                'spotify_url' => null,
                'youtube_url' => null,
                'deezer_url' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);
    }
}
