<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PartenaireSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('partenaires')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $now = date('Y-m-d H:i:s');

        DB::table('partenaires')->insert([
            [
                'id' => 1,
                'name' => 'Le Grand Lunetier',
                'description' => 'Votre opticien de proximité pour un accompagnement sur mesure. Profitez d\'une expertise complète : contrôle de la vue, conseils en visagisme, vente et réparation de lunettes ou lentilles.',
                'logo' => 'img/partners/logos/Le Grand Lunetier.webp',
                'photo' => null,
                'site_url' => 'https://legrandlunetier.fr/',
                'instagram_url' => 'https://www.instagram.com/legrandlunetier/?hl=fr',
                'facebook_url' => 'https://www.facebook.com/LGLPontchateau/?locale=fr_FR',
                'linkedin_url' => null,
                'autre_url' => null,
                'phone' => '02 40 88 14 66',
                'adresse' => '1 Rue de Nantes',
                'ville' => 'Pontchâteau',
                'departement' => null,
                'code_postal' => '44160',
                'pays' => 'France',
                'latitude' => '47.43719750',
                'longitude' => '-2.08957160',
                'ordre' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 2,
                'name' => 'Merzhin Production',
                'description' => 'Prestataire évènementiel',
                'logo' => null,
                'photo' => null,
                'site_url' => null,
                'instagram_url' => null,
                'facebook_url' => 'https://m.facebook.com/p/Merzhin-Production-61554676089339/',
                'linkedin_url' => null,
                'autre_url' => null,
                'phone' => '07 81 63 00 64',
                'adresse' => '68 Rue de la Gare',
                'ville' => 'Saint-Gildas-des-Bois',
                'departement' => null,
                'code_postal' => '44530',
                'pays' => 'France',
                'latitude' => '47.51689900',
                'longitude' => '-2.04350800',
                'ordre' => 2,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 3,
                'name' => 'Paul & Joseph',
                'description' => 'Cave & Bar',
                'logo' => null,
                'photo' => null,
                'site_url' => 'https://www.pauletjoseph.fr/',
                'instagram_url' => null,
                'facebook_url' => 'https://www.facebook.com/photo.php?fbid=1587669938053267&id=226807257472882&set=a.248854148601526&locale=fr_FR',
                'linkedin_url' => 'https://fr.linkedin.com/company/paul-et-joseph',
                'autre_url' => null,
                'phone' => '02 40 69 09 56',
                'adresse' => 'ZAC de la Colleraye',
                'ville' => 'Savenay',
                'departement' => null,
                'code_postal' => '44260',
                'pays' => 'France',
                'latitude' => '47.37406600',
                'longitude' => '-1.93530500',
                'ordre' => 3,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 4,
                'name' => 'Judic Mécanique Automobiles',
                'description' => 'Votre spécialiste local en mécanique automobile. Profitez d\'un service de proximité pour l\'entretien, le diagnostic et la réparation de tous vos véhicules.',
                'logo' => 'img/partners/logos/Judic Mécanique Automobiles.webp',
                'photo' => null,
                'site_url' => null,
                'instagram_url' => null,
                'facebook_url' => null,
                'linkedin_url' => null,
                'autre_url' => null,
                'phone' => '02 40 33 57 31',
                'adresse' => '29 La Mercerie',
                'ville' => 'Campbon',
                'departement' => null,
                'code_postal' => '44750',
                'pays' => 'France',
                'latitude' => '47.42994600',
                'longitude' => '-1.99709700',
                'ordre' => 4,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 5,
                'name' => 'Aimantik',
                'description' => 'Bijoux Switchables Pour Homme',
                'logo' => null,
                'photo' => null,
                'site_url' => null,
                'instagram_url' => 'https://www.instagram.com/aimantik/',
                'facebook_url' => null,
                'linkedin_url' => null,
                'autre_url' => null,
                'phone' => null,
                'adresse' => null,
                'ville' => 'La Baule',
                'departement' => null,
                'code_postal' => null,
                'pays' => 'France',
                'latitude' => null,
                'longitude' => null,
                'ordre' => 5,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 6,
                'name' => 'JGM Événements',
                'description' => 'Régisseur et prestataire technique de confiance. Déjà présent lors de la précédente édition, JGM Événements assure à nouveau toute la régie technique du festival pour une expérience sonore et visuelle unique.',
                'logo' => 'img/partners/logos/JGM Événements.webp',
                'photo' => null,
                'site_url' => null,
                'instagram_url' => 'https://www.instagram.com/jgmevent/',
                'facebook_url' => 'https://www.facebook.com/JGMEvenements/',
                'linkedin_url' => 'https://fr.linkedin.com/company/jgmevent',
                'autre_url' => null,
                'phone' => '02 40 13 85 85',
                'adresse' => '68 rue de la gare, La Croix Daniel ZA',
                'ville' => 'Saint-Gildas-des-Bois',
                'departement' => null,
                'code_postal' => '44530',
                'pays' => 'France',
                'latitude' => null,
                'longitude' => null,
                'ordre' => 6,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 7,
                'name' => 'Violin Peinture SARL',
                'description' => 'Spécialiste de proximité en peinture et décoration pour les particuliers et les industriels. Une entreprise locale reconnue pour ses prestations complètes et ses finitions de qualité.',
                'logo' => 'img/partners/logos/Violin SARL.webp',
                'photo' => null,
                'site_url' => 'https://www.violin-peinture.fr/',
                'instagram_url' => 'https://www.instagram.com/entviolinsarl',
                'facebook_url' => 'https://www.facebook.com/EntrepriseVIOLINSarl/',
                'linkedin_url' => null,
                'autre_url' => 'https://linktr.ee/entviolinsarl',
                'phone' => '02 40 56 51 51',
                'adresse' => '2 Rue de Saint-Nazaire',
                'ville' => 'Campbon',
                'departement' => '44',
                'code_postal' => '44750',
                'pays' => 'France',
                'latitude' => '47.41383600',
                'longitude' => '-1.97222900',
                'ordre' => 7,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 8,
                'name' => 'NH multiservices',
                'description' => 'Plomberies & Electricité',
                'logo' => null,
                'photo' => null,
                'site_url' => null,
                'instagram_url' => null,
                'facebook_url' => null,
                'linkedin_url' => null,
                'autre_url' => null,
                'phone' => '06 86 47 71 65',
                'adresse' => null,
                'ville' => 'Blain',
                'departement' => null,
                'code_postal' => null,
                'pays' => 'France',
                'latitude' => null,
                'longitude' => null,
                'ordre' => 8,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 9,
                'name' => 'Utile Malville',
                'description' => 'Votre supermarché U de proximité ouvert 7j/7. Un magasin de confiance offrant une large variété de produits de qualité pour répondre à tous vos besoins du quotidien.',
                'logo' => 'img/partners/logos/Utile Malville.webp',
                'photo' => null,
                'site_url' => 'https://www.magasins-u.com/',
                'instagram_url' => null,
                'facebook_url' => 'https://www.facebook.com/utilemalvile44/?locale=fr_FR',
                'linkedin_url' => null,
                'autre_url' => null,
                'phone' => '02 40 56 08 96',
                'adresse' => 'Rue des Musiciens',
                'ville' => 'Malville',
                'departement' => '44',
                'code_postal' => '44260',
                'pays' => 'France',
                'latitude' => '47.35917000',
                'longitude' => '-1.86175400',
                'ordre' => 9,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 10,
                'name' => 'Thélem assurances Pontchâteau',
                'description' => 'Votre assureur de proximité à Pontchâteau. Une équipe locale et à l’écoute pour vous proposer des solutions d’assurance adaptées à votre quotidien, en toute confiance.',
                'logo' => 'img/partners/logos/Thélem assurances Pontchâteau.webp',
                'photo' => null,
                'site_url' => 'https://www.thelem-assurances.fr/agences/pontchateau/',
                'instagram_url' => null,
                'facebook_url' => 'https://www.facebook.com/thelem.assurances/?locale=fr_FR',
                'linkedin_url' => 'https://fr.linkedin.com/company/thelem-assurances',
                'autre_url' => null,
                'phone' => '02 51 10 78 39',
                'adresse' => '26 Rue Sainte-Catherine',
                'ville' => 'Pontchâteau',
                'departement' => '44',
                'code_postal' => '44160',
                'pays' => 'France',
                'latitude' => '47.43564900',
                'longitude' => '-2.09017980',
                'ordre' => 10,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 11,
                'name' => 'Ingrand Bol d’air',
                'description' => 'Spécialiste de proximité dans l\'aménagement et l\'entretien de vos espaces verts. Profitez d\'un service de qualité et des avantages fiscaux liés aux services à la personne.',
                'logo' => 'img/partners/logos/Ingrand Bol d’air.webp',
                'photo' => null,
                'site_url' => 'https://www.ingrand-boldair.fr',
                'instagram_url' => null,
                'facebook_url' => null,
                'linkedin_url' => null,
                'autre_url' => null,
                'phone' => '06 38 39 36 22',
                'adresse' => '28 Rue du Moulin des Epinettes',
                'ville' => 'Savenay',
                'departement' => '44',
                'code_postal' => '44260',
                'pays' => 'France',
                'latitude' => '47.36716640',
                'longitude' => '-1.95216920',
                'ordre' => 11,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 13,
                'name' => 'Louvert & fils',
                'description' => 'Experts en électricité générale et chauffage depuis 1946. Une entreprise historique qui met son savoir-faire au service de vos installations, de votre chauffage et de votre ventilation.',
                'logo' => 'img/partners/logos/Louvert & fils.webp',
                'photo' => null,
                'site_url' => null,
                'instagram_url' => null,
                'facebook_url' => null,
                'linkedin_url' => null,
                'autre_url' => null,
                'phone' => '02 40 58 31 06',
                'adresse' => '12 Pl. Saint-Martin',
                'ville' => 'Savenay',
                'departement' => '44',
                'code_postal' => '44260',
                'pays' => 'France',
                'latitude' => '47.36101500',
                'longitude' => '-1.94564600',
                'ordre' => 12,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 14,
                'name' => 'Nicolas Houguet Multi-services',
                'description' => 'Votre artisan multiservices de confiance. Spécialiste de proximité pour tous vos travaux et dépannages en plomberie et électricité.',
                'logo' => 'img/partners/logos/Nicolas Houguet Multi-services.webp',
                'photo' => null,
                'site_url' => null,
                'instagram_url' => null,
                'facebook_url' => null,
                'linkedin_url' => null,
                'autre_url' => null,
                'phone' => '06 86 47 71 65',
                'adresse' => null,
                'ville' => 'Blain',
                'departement' => '44',
                'code_postal' => '44130',
                'pays' => 'France',
                'latitude' => null,
                'longitude' => null,
                'ordre' => 13,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 16,
                'name' => 'CrossFit Alvilda',
                'description' => 'Bien plus qu’une salle de sport ! Profitez d\'un accompagnement personnalisé avec un coach pour bouger, progresser et améliorer votre bien-être au quotidien.',
                'logo' => 'img/partners/logos/CrossFit Alvilda.webp',
                'photo' => null,
                'site_url' => 'https://www.crossfit-alvilda.bzh/',
                'instagram_url' => 'https://www.instagram.com/crossfitalvilda',
                'facebook_url' => 'https://www.facebook.com/p/Crossfit-Alvilda-61575851467894/',
                'linkedin_url' => null,
                'autre_url' => 'https://linktr.ee/entviolinsarl',
                'phone' => '06 73 49 59 30',
                'adresse' => 'ZA du Parc',
                'ville' => 'Muzillac',
                'departement' => '56',
                'code_postal' => '56190',
                'pays' => 'France',
                'latitude' => null,
                'longitude' => null,
                'ordre' => 14,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);
    }
}
