<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PartenaireSeeder extends Seeder
{
    public function run()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('partenaires')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $now = date('Y-m-d H:i:s');

        DB::table('partenaires')->insert([
            [
                'name' => 'Le Grand Lunetier',
                'description' => 'Magasin de lunettes et lunettes de soleil',
                'logo' => null,
                'photo' => null,
                'site_url' => null,
                'instagram_url' => 'https://www.instagram.com/legrandlunetier/?hl=fr',
                'facebook_url' => 'https://www.facebook.com/LGLPontchateau/?locale=fr_FR',
                'linkedin_url' => null,
                'autre_url' => null,
                'phone' => '02 40 88 14 66',
                'adresse' => '1 Rue de Nantes',
                'ville' => 'Pontchâteau',
                'departement' => null,
                'code_postal' => '44160',
                'pays' => 'France',
                'latitude' => 47.437198,
                'longitude' => -2.089572,
                'ordre' => 1,
                'annee' => 2025,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Merzhin Production',
                'description' => 'Prestataire évènementiel',
                'logo' => null,
                'photo' => null,
                'site_url' => null,
                'instagram_url' => null,
                'facebook_url' => 'https://m.facebook.com/p/Merzhin-Production-61554676089339/',
                'linkedin_url' => null,
                'autre_url' => null,
                'phone' => '07 81 63 00 64',
                'adresse' => '68 Rue de la Gare',
                'ville' => 'Saint-Gildas-des-Bois',
                'departement' => null,
                'code_postal' => '44530',
                'pays' => 'France',
                'latitude' => 47.516899,
                'longitude' => -2.043508,
                'ordre' => 2,
                'annee' => 2025,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Paul & Joseph',
                'description' => 'Cave & Bar',
                'logo' => null,
                'photo' => null,
                'site_url' => 'https://www.pauletjoseph.fr/',
                'instagram_url' => null,
                'facebook_url' => 'https://www.facebook.com/photo.php?fbid=1587669938053267&id=226807257472882&set=a.248854148601526&locale=fr_FR',
                'linkedin_url' => 'https://fr.linkedin.com/company/paul-et-joseph',
                'autre_url' => null,
                'phone' => '02 40 69 09 56',
                'adresse' => 'ZAC de la Colleraye',
                'ville' => 'Savenay',
                'departement' => null,
                'code_postal' => '44260',
                'pays' => 'France',
                'latitude' => 47.374066,
                'longitude' => -1.935305,
                'ordre' => 3,
                'annee' => 2025,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Judic Mécanique Automobiles',
                'description' => 'Mécanique automobile',
                'logo' => null,
                'photo' => null,
                'site_url' => null,
                'instagram_url' => null,
                'facebook_url' => null,
                'linkedin_url' => null,
                'autre_url' => null,
                'phone' => '02 40 33 57 31',
                'adresse' => '29 La Mercerie',
                'ville' => 'Campbon',
                'departement' => null,
                'code_postal' => '44750',
                'pays' => 'France',
                'latitude' => 47.429946,
                'longitude' => -1.997097,
                'ordre' => 4,
                'annee' => 2025,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Aimantik',
                'description' => 'Bijoux Switchables Pour Homme',
                'logo' => null,
                'photo' => null,
                'site_url' => null,
                'instagram_url' => 'https://www.instagram.com/aimantik/',
                'facebook_url' => null,
                'linkedin_url' => null,
                'autre_url' => null,
                'phone' => null,
                'adresse' => null,
                'ville' => 'La Baule',
                'departement' => null,
                'code_postal' => null,
                'pays' => 'France',
                'latitude' => null,
                'longitude' => null,
                'ordre' => 5,
                'annee' => 2025,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'JGM Evenements',
                'description' => 'Prestataire technique : son, régie, logistique & distribution électrique',
                'logo' => null,
                'photo' => null,
                'site_url' => null,
                'instagram_url' => 'https://www.instagram.com/jgmevent/',
                'facebook_url' => 'https://www.facebook.com/JGMEvenements/',
                'linkedin_url' => 'https://fr.linkedin.com/company/jgmevent',
                'autre_url' => null,
                'phone' => '02 40 13 85 85',
                'adresse' => '68 rue de la gare, La Croix Daniel ZA',
                'ville' => 'Saint-Gildas-des-Bois',
                'departement' => null,
                'code_postal' => '44530',
                'pays' => 'France',
                'latitude' => null,
                'longitude' => null,
                'ordre' => 6,
                'annee' => 2025,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Entreprise Violin Peinture',
                'description' => 'Peintre',
                'logo' => null,
                'photo' => null,
                'site_url' => null,
                'instagram_url' => 'https://www.instagram.com/entviolinsarl/',
                'facebook_url' => 'https://www.facebook.com/EntrepriseVIOLINSarl/',
                'linkedin_url' => null,
                'autre_url' => null,
                'phone' => '02 40 56 51 51',
                'adresse' => '2 Rue de Saint-Nazaire',
                'ville' => 'Campbon',
                'departement' => null,
                'code_postal' => '44750',
                'pays' => 'France',
                'latitude' => 47.413889,
                'longitude' => -1.972212,
                'ordre' => 7,
                'annee' => 2025,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'NH multiservices',
                'description' => 'Plomberies & Electricité',
                'logo' => null,
                'photo' => null,
                'site_url' => null,
                'instagram_url' => null,
                'facebook_url' => null,
                'linkedin_url' => null,
                'autre_url' => null,
                'phone' => '06 86 47 71 65',
                'adresse' => null,
                'ville' => 'Blain',
                'departement' => null,
                'code_postal' => null,
                'pays' => 'France',
                'latitude' => null,
                'longitude' => null,
                'ordre' => 8,
                'annee' => 2025,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Utile',
                'description' => 'Supermarché',
                'logo' => null,
                'photo' => null,
                'site_url' => null,
                'instagram_url' => null,
                'facebook_url' => 'https://www.facebook.com/utilemalvile44/?locale=fr_FR',
                'linkedin_url' => null,
                'autre_url' => null,
                'phone' => '02 40 56 08 96',
                'adresse' => 'Rue des Musiciens',
                'ville' => 'Malville',
                'departement' => null,
                'code_postal' => '44260',
                'pays' => 'France',
                'latitude' => 47.35917,
                'longitude' => -1.861754,
                'ordre' => 9,
                'annee' => 2025,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => "Thélem Assurance (PontChâteau)",
                'description' => 'Assurances',
                'logo' => null,
                'photo' => null,
                'site_url' => null,
                'instagram_url' => null,
                'facebook_url' => 'https://www.facebook.com/thelem.assurances/?locale=fr_FR',
                'linkedin_url' => 'https://fr.linkedin.com/company/thelem-assurances',
                'autre_url' => null,
                'phone' => '02 51 10 78 39',
                'adresse' => '26 Rue Sainte-Catherine',
                'ville' => 'Pontchâteau',
                'departement' => null,
                'code_postal' => '44160',
                'pays' => 'France',
                'latitude' => 47.435649,
                'longitude' => -2.09018,
                'ordre' => 10,
                'annee' => 2025,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);
    }
}
