<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PerformanceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Désactiver contraintes FK pour permettre truncate
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('performances')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $now = Carbon::now();

        // Récupère la première édition
        $edition = DB::table('editions')->first();

        DB::table('performances')->insert([
            [
                'edition_id' => $edition->id,
                'artiste_id' => 1,
                'begin_date' => '2025-09-12 20:00:00',
                'ending_date' => '2025-09-12 21:30:00',
                'scene' => 'Extérieur',
                'day' => 'Vendredi',
                'actif' => true,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'edition_id' => $edition->id,
                'artiste_id' => 2,
                'day' => 'Vendredi',
                'begin_date' => '2025-09-12 21:00:00',
                'ending_date' => '2025-09-12 22:30:00',
                'scene' => 'Intérieur',
                'actif' => true,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'edition_id' => $edition->id,
                'artiste_id' => 3,
                'day' => 'Vendredi',
                'begin_date' => '2025-09-12 22:30:00',
                'ending_date' => '2025-09-13 00:00:00',
                'scene' => 'Extérieur',
                'actif' => true,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'edition_id' => $edition->id,
                'artiste_id' => 4,
                'day' => 'Vendredi',
                'begin_date' => '2025-09-13 00:00:00',
                'ending_date' => '2025-09-13 02:00:00',
                'scene' => 'Extérieur',
                'actif' => true,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'edition_id' => $edition->id,
                'artiste_id' => 5,
                'day' => 'Vendredi',
                'begin_date' => '2025-09-13 00:30:00',
                'ending_date' => '2025-09-13 02:00:00',
                'scene' => 'Intérieur',
                'actif' => true,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'edition_id' => $edition->id,
                'artiste_id' => 6,
                'day' => 'Vendredi',
                'begin_date' => '2025-09-13 02:00:00',
                'ending_date' => '2025-09-13 04:00:00',
                'scene' => 'Extérieur',
                'actif' => true,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'edition_id' => $edition->id,
                'artiste_id' => 7,
                'day' => 'Vendredi',
                'begin_date' => '2025-09-13 02:00:00',
                'ending_date' => '2025-09-13 03:30:00',
                'scene' => 'Intérieur',
                'actif' => true,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'edition_id' => $edition->id,
                'artiste_id' => 8,
                'day' => 'Samedi',
                'begin_date' => '2025-09-13 15:00:00',
                'ending_date' => '2025-09-13 17:00:00',
                'scene' => 'Extérieur',
                'actif' => true,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'edition_id' => $edition->id,
                'artiste_id' => 9,
                'day' => 'Samedi',
                'begin_date' => '2025-09-13 17:00:00',
                'ending_date' => '2025-09-13 18:30:00',
                'scene' => 'Extérieur',
                'actif' => true,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'edition_id' => $edition->id,
                'artiste_id' => 10,
                'day' => 'Samedi',
                'begin_date' => '2025-09-13 18:30:00',
                'ending_date' => '2025-09-13 19:30:00',
                'scene' => 'Extérieur',
                'actif' => true,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'edition_id' => $edition->id,
                'artiste_id' => 11,
                'day' => 'Samedi',
                'begin_date' => '2025-09-13 19:30:00',
                'ending_date' => '2025-09-13 21:00:00',
                'scene' => 'Extérieur',
                'actif' => true,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'edition_id' => $edition->id,
                'artiste_id' => 12,
                'day' => 'Samedi',
                'begin_date' => '2025-09-13 20:30:00',
                'ending_date' => '2025-09-13 22:00:00',
                'scene' => 'Intérieur',
                'actif' => true,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'edition_id' => $edition->id,
                'artiste_id' => 13,
                'day' => 'Samedi',
                'begin_date' => '2025-09-13 22:00:00',
                'ending_date' => '2025-09-13 23:30:00',
                'scene' => 'Extérieur',
                'actif' => true,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'edition_id' => $edition->id,
                'artiste_id' => 14,
                'day' => 'Samedi',
                'begin_date' => '2025-09-13 23:30:00',
                'ending_date' => '2025-09-14 02:00:00',
                'scene' => 'Extérieur',
                'actif' => true,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'edition_id' => $edition->id,
                'artiste_id' => 15,
                'day' => 'Samedi',
                'begin_date' => '2025-09-14 00:30:00',
                'ending_date' => '2025-09-14 02:00:00',
                'scene' => 'Intérieur',
                'actif' => true,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'edition_id' => $edition->id,
                'artiste_id' => 16,
                'day' => 'Samedi',
                'begin_date' => '2025-09-14 02:00:00',
                'ending_date' => '2025-09-14 04:00:00',
                'scene' => 'Extérieur',
                'actif' => true,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'edition_id' => $edition->id,
                'artiste_id' => 17,
                'day' => 'Samedi',
                'begin_date' => '2025-09-14 02:00:00',
                'ending_date' => '2025-09-14 03:30:00',
                'scene' => 'Intérieur',
                'actif' => true,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'edition_id' => $edition->id,
                'artiste_id' => 18,
                'day' => 'Samedi',
                'begin_date' => '2025-09-13 20:00:00',
                'ending_date' => '2025-09-13 21:00:00',
                'scene' => 'Intérieur',
                'actif' => true,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);
    }
}
