<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductsImageSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('products_images')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $now = date('Y-m-d H:i:s');

        DB::table('products_images')->insert([
            [
                'id' => 1,
                'product_id' => 1,
                'variant_id' => 1,
                'image' => 'img/boutique/products/tshirt-souvenir-2025_violet_1.jpg',
                'ordre' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 2,
                'product_id' => 1,
                'variant_id' => 1,
                'image' => 'img/boutique/products/tshirt-souvenir-2025_violet_2.jpg',
                'ordre' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 3,
                'product_id' => 1,
                'variant_id' => 1,
                'image' => 'img/boutique/products/tshirt-souvenir-2025_violet_3.jpg',
                'ordre' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 4,
                'product_id' => 1,
                'variant_id' => 1,
                'image' => 'img/boutique/products/tshirt-souvenir-2025_violet_4.jpg',
                'ordre' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 5,
                'product_id' => 1,
                'variant_id' => 1,
                'image' => 'img/boutique/products/tshirt-souvenir-2025_violet_5.jpg',
                'ordre' => 5,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 6,
                'product_id' => 2,
                'variant_id' => 7,
                'image' => 'img/boutique/products/tshirt-officiel-2026_bleu_1.jpg',
                'ordre' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 7,
                'product_id' => 2,
                'variant_id' => 7,
                'image' => 'img/boutique/products/tshirt-officiel-2026_bleu_2.jpg',
                'ordre' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 8,
                'product_id' => 2,
                'variant_id' => 7,
                'image' => 'img/boutique/products/tshirt-officiel-2026_bleu_3.jpg',
                'ordre' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 9,
                'product_id' => 2,
                'variant_id' => 7,
                'image' => 'img/boutique/products/tshirt-officiel-2026_bleu_4.jpg',
                'ordre' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 10,
                'product_id' => 2,
                'variant_id' => 7,
                'image' => 'img/boutique/products/tshirt-officiel-2026_bleu_5.jpg',
                'ordre' => 5,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 11,
                'product_id' => 3,
                'variant_id' => 13,
                'image' => 'img/boutique/products/tshirt-classique_blanc_1.jpg',
                'ordre' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 12,
                'product_id' => 3,
                'variant_id' => 13,
                'image' => 'img/boutique/products/tshirt-classique_blanc_2.jpg',
                'ordre' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 13,
                'product_id' => 3,
                'variant_id' => 13,
                'image' => 'img/boutique/products/tshirt-classique_blanc_3.jpg',
                'ordre' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 14,
                'product_id' => 3,
                'variant_id' => 13,
                'image' => 'img/boutique/products/tshirt-classique_blanc_4.jpg',
                'ordre' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 15,
                'product_id' => 3,
                'variant_id' => 13,
                'image' => 'img/boutique/products/tshirt-classique_blanc_5.jpg',
                'ordre' => 5,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 16,
                'product_id' => 4,
                'variant_id' => 19,
                'image' => 'img/boutique/products/pull-demi-zip_vert_1.jpg',
                'ordre' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 17,
                'product_id' => 5,
                'variant_id' => 25,
                'image' => 'img/boutique/products/pull-demi-zip-officiel_bleu_1.jpg',
                'ordre' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 18,
                'product_id' => 6,
                'variant_id' => 31,
                'image' => 'img/boutique/products/sweat-capuche-officiel_bleu_1.jpg',
                'ordre' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 19,
                'product_id' => 7,
                'variant_id' => 38,
                'image' => 'img/boutique/products/lunettes-calan_bleu_1.jpg',
                'ordre' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 20,
                'product_id' => 7,
                'variant_id' => 38,
                'image' => 'img/boutique/products/lunettes-calan_bleu_2.jpg',
                'ordre' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 21,
                'product_id' => 7,
                'variant_id' => 37,
                'image' => 'img/boutique/products/lunettes-calan_rouge_1.jpg',
                'ordre' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 22,
                'product_id' => 7,
                'variant_id' => 37,
                'image' => 'img/boutique/products/lunettes-calan_rouge_2.jpg',
                'ordre' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 23,
                'product_id' => 8,
                'variant_id' => null,
                'image' => 'img/boutique/products/tot-bag_blanc_1.jpg',
                'ordre' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 24,
                'product_id' => 9,
                'variant_id' => 40,
                'image' => 'img/boutique/products/bob-officiel-2026_bleu_1.jpg',
                'ordre' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 25,
                'product_id' => 10,
                'variant_id' => 41,
                'image' => 'img/boutique/products/casquette-officielle-2026_bleu_1.jpg',
                'ordre' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 26,
                'product_id' => 11,
                'variant_id' => 42,
                'image' => 'img/boutique/products/gourde-25cl_1.jpg',
                'ordre' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 27,
                'product_id' => 11,
                'variant_id' => 42,
                'image' => 'img/boutique/products/gourde-25cl_2.jpg',
                'ordre' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 28,
                'product_id' => 11,
                'variant_id' => 42,
                'image' => 'img/boutique/products/gourde-25cl_3.jpg',
                'ordre' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 29,
                'product_id' => 12,
                'variant_id' => null,
                'image' => 'img/boutique/products/bandana_violet_1.jpg',
                'ordre' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);
    }
}
